### ISSUE TITLE
Support for APPLE extensions

### ISSUE THREAD

**Issue by DDoS** [DerelictOrg/DerelictGL3#28]
Some important APPLE extensions are missing. One major example is vertex array objects in OpenGL 2. ARB_vertex_array_object isn't supported, so no VAOs are available on OS X when using OpenGL 2. Instead [APPLE_vertex_array_object](https://www.opengl.org/registry/specs/APPLE/vertex_array_object.txt) must be used.

**Comment by aldacron** [comment]
All Apple extensions are missing :) I only add support for non-ARB extensions when there are requests for them. Helps keep the source streamlined and the maintenance cost lower. Is the VAO extension the only one you need? If not, let me know and I'll get them all in one go.

**Comment by DDoS** [comment]
I only need VAO for my project.

**Comment by aldacron** [comment]
Sorry, I meant to take care of this after work the other day but it slipped my mind. I've tagged 1.0.12 and the DUB registry has picked it up, so you're all set.
