### ISSUE TITLE
Deprecated functions and constants visible when importing gl3.d.

### ISSUE THREAD

**Issue by Entity325** [DerelictOrg/DerelictGL3#29]
Libraries used
DerelictSDL2-master latest version
DerelictGL3-master latest version
DerelictUtil-2.0 latest version(last I checked, the master branch didn't have the minimum version feature included yet, though that was more than a month ago)

Libraries and executable compiled using DMD 2.066.1

Source code:
```D
import std.stdio;
import std.string;
import std.conv;

import core.memory;
import core.exception;

import derelict.sdl2.sdl;

import derelict.opengl3.gl;

import core.time;
import core.exception;

const int xResolution = 800;
const int yResolution = 600;

// number of bits per pixel used for display. 24 => true color
const int bitsPerPixel      = 32;


int main(string[] args)
{
    //Engine engine = new Engine();
    init();
    writeln("Press Enter to close.");
    readln();
    writeln("Program exited safely.");
    return 0;
}


bool init()
{
    //IO and basic graphics.  Needed everywhere.
    DerelictSDL2.load();

    //OGL graphics.  Needed for window and drawing.
    DerelictGL3.load();

    // create our OpenGL window
    //window = new Window(xResolution, yResolution, bitsPerPixel, false, "My SDL Window", [Rectf(0,0,1,1)]);
    //inlining for science.
////////////////////

        if( SDL_Init( SDL_INIT_VIDEO ) != 0 )
        {
            writeln("SDL Video initialization failed.");
            return false;
        }
        bool fullscreen = false;
        int bpp = bitsPerPixel;

        SDL_Window* thisWindow;
        SDL_GLContext glContext;

        writeln("Starting window at size ", xResolution, ", ", yResolution, (fullscreen ? " in full-screen," : " windowed,"), " at ", bpp, " bits per pixel.");

        // Flags tell SDL about the type of window we are creating.
        int windowFlags = SDL_WINDOW_OPENGL;//|SDL_WINDOW_RESIZABLE;
        if(fullscreen)
            windowFlags |= SDL_WINDOW_FULLSCREEN_DESKTOP;


//            SDL_SetVideoMode( sdlvideoinfo.current_w, sdlvideoinfo.current_h, bpp, flags );
        thisWindow = SDL_CreateWindow("My SDL Window",
                                      SDL_WINDOWPOS_UNDEFINED,
                                      SDL_WINDOWPOS_UNDEFINED,
                                      xResolution, yResolution,
                                      windowFlags);
        if(thisWindow is null)
        {
            writeln("Window failed to be created.");
            return false;
        }
        writeln("Window created.");

        glContext = SDL_GL_CreateContext(thisWindow);

        GLVersion glVersion = DerelictGL.reload();
        if(glVersion > GLVersion.GL20)
        {
            writeln("Sufficient OpenGL version found.");
            writeln("Loaded OGL version is: ", glVersion);
            string glVersionStr = to!(string)(glGetString( GL_VERSION ));
            writeln("GL version reported as ", glVersionStr);
        }
        else
        {
            writeln("Error: OpenGL version ", glVersion, " not supported.");
            glContext = null;
        }
        if(glMatrixMode is null)
            writeln("ERROR! glMatrixMode not loaded! (And likely neither are a lot of other GL functions.)");
        else
            writeln("All functions loaded properly.");

////////////////////
    int errorCode = glGetError();
    if(errorCode != GL_NO_ERROR)
        writeln("Error!  Something happened during window creation.");
    while(errorCode != GL_NO_ERROR)
    {
        writeln("Error: ", errorCode);
        errorCode = glGetError();
    }
//clean up.
    SDL_Quit();
    DerelictSDL2.unload();
    DerelictGL3.unload();
    return true;
}
```

Window appears and then disappears(desired behavior)
Console output seen in screenshot. Error message indicates symbols not loaded, and is not desired 
![clipboard-1](https://cloud.githubusercontent.com/assets/10861954/6056480/ad42721e-acce-11e4-999b-32103216d9d0.png)
behavior.

**Comment by aldacron** [comment]
I've edited your post to get the source code properly formatted. I'd also like to point out that a) you've called glGetString, which is loaded by the load() method and that b) reload() uses some internal functions that also depend on functions loaded in the load() method. If load were not working properly, you would have found yourself with an access violation. I'm going to copy the code right now and see what happens.

**Comment by aldacron** [comment]
OK, the functions are loading just fine. When I saw your post on the newsgroup, something was tickling the back of my mind, but I didn't catch it -- glMatrixMode is a deprecated function. DerelictGL3.load doesn't even load it. It is declared in deprecatedFunctions.d and loaded by the DerelictGL loader in gl.d. Since you're using DerelictGL3 and not DerelictGL, it is never loaded. Nor should it be.

The puzzling part for me is that this shouldn't even be visible unless you import derelict.opengl3.gl (or the deprecatedFunctions module directly). I can't figure out how it's possible to even test it for null without a compiler error. Something is wonky somewhere.

At any rate, you have no worry. Everything is loading fine. I would like to emphasize that when functions aren't loaded, you'll get an access violation when trying to call them. If that isn't happening, then you can be sure the ones you're calling are loaded. I'll leave this issue open though (with a new title), until I can figure out how a symbol that is never imported can be visible.

**Comment by aldacron** [comment]
Oh, I should also point out that no only is it not necessary to call unload on any Derelict loaders at program exit, it's actually a bad idea. The OS is going to clean it up when the process exits, so you don't need to. But if you do unload them and then later on start calling into the libraries through destructors, you'll see access violations when the program exists -- your destructors will be called as the GC is cleaning up, but the libraries will already have been unloaded. Just let the OS take care of it.

**Comment by Entity325** [comment]
So THAT'S why I kept seeing access violations on program exit while still using Derelict 1.

If I switch the import library from opengl3.gl to opengl3.gl3 in my current test program, I get a compile error on glMatrixMode, so apparently I'm doing some wonky imports elsewhere.(and this issue can probably be marked resolved.)

I do kind of need access to deprecated functions in the project I'm working on, so I'll have to stick with gl.d for now, but I am still getting the access violation on execution. Is there something else I need to call to ensure deprecated functions get loaded?

**Comment by mathstuf** [comment]
@Entity325 use `DerelictGL.load()` rather than `DerelictGL3.load()`.

**Comment by Entity325** [comment]
That fixed it, thanks.

**Comment by aldacron** [comment]
Well, don't I feel silly now. I swear I looked at those imports a dozen times trying to figure out why glMatrixMode was visible and I was certain you were importing the gl3 module and not the gl module.
