### ISSUE TITLE
Mark load and reload with @nogc

### ISSUE THREAD

**Issue by Dgame** [DerelictOrg/DerelictGL3#30]
Is this possible?

**Comment by mathstuf** [comment]
The extension cache seems to use the GC, so this might not be possible without rewriting that bit.

**Comment by aldacron** [comment]
Marking the load method @nogc would require rewriting the loader in DerelictUtil, in addition to the extension cache for the reload method. I'm not really interested in doing that unless someone can show me there's a massive benefit from doing so. D has a GC for a reason and I'm not going to go out of my way to avoid it unless I need to.

**Comment by mathstuf** [comment]
The only thing I can think of is that the GC seems to be the cause of my Android woes, but that's just a hunch; no actual data. In terms of better supported systems, the GC usage just for setup is likely fine, I feel, for most cases (@nogc your main loop and do the bootstrapping stuff before it).

**Comment by aldacron** [comment]
Right, that exactly mirrors my thoughts about @nogc. From my perspective, it doesn't make much sense to mark the entire app @nogc outside of a few very specific cases.

**Comment by Dgame** [comment]
You can't mark a loop with @nogc. Only functions and method can be marked. Therefore I thought it would be awesome if I could use Derelict in a function which is marked @nogc. ;)

**Comment by aldacron** [comment]
He's not talking about an actual loop construct, but something like this:
```D
init() {}
@nogc run() {}
```
All of the initialization that requires GC, like DerelictGL3.load and such, goes in the 'init' call chain. The main loop and everything else goes in the 'run' call chain. You don't need to be calling any Derelict load methods from the main loop. And if you're using multiple OpenGL contexts, you can set up an event-based callback mechanism before entering the main loop. That way, your @nogc code never has to touch DerelictGL3.reload.

**Comment by Dgame** [comment]
I'm creating a GL Context inside of a constructor. Then (after that creation) I have to call init, which also contains the Derelict.reload call. So init cannot be @nogc and therefore not the constructor. I don't see how I could separate that, without using a global pointer. Did you see a way, how I could define the constructor @nogc?

**Comment by aldacron** [comment]
The question is, why do you want to? What we're recommending is that initialization *not* be @nogc, which is what you have. Why does your constructor need to be @nogc?

**Comment by Dgame** [comment]
I'm just asking if it is possible.
