### ISSUE TITLE
Derelict GL3 throws SymbolLoadException trying to load unavailable function

### ISSUE THREAD

**Issue by ParticlePeter** [DerelictOrg/DerelictGL3#32]
VS2013, exception pops up only if debugging with Mago:
First-chance exception: derelict.util.exception.SymbolLoadException Failed to load OpenGL symbol [glEnableClientStateiEXT] at DerelictUtil\source\derelict\util\exception.d(35)

This is happening while loading all functions related to EXT_direct_state_access ( which is written against GL 2.1 not to be confused with ARB_direct_state_access written against GL4.4 ).

DerelictGLFW is used as windowing system with GLFW_OPENGL_CORE_PROFILE, requested version 3.3. The driver is GL 4.4 able, hence derelict loads up to that version. DerelictGL3 Version Tag is 1.0.12.

Hope my interpretation of DerelictGL3.ext.d is right. All function pointers from ext.d load_EXT_direct_state_access ( line 1163 ) are loaded till glEnableClientStateiEXT ( line 1247 ), which they shouldn't as I would not expect those functions in core profile. load_EXT_direct_state_access should not load at all in core profile.

In my case the exception can be ignored, and program can be continued, as I do not use any of these function pointers.

**Comment by aldacron** [comment]
Sorry, this fell off my radar. The thing is, any exception thrown inside that function should be caught down at the bottom (line 1433). The fact that it's only happening when debugging with Mago leads to me to believe it's not a general problem with Derelict, but something specific to the interaction between the two. You might want to run this by Rainer or whomever is maintaining Mago right now. Not sure what I can do on my end.
