### ISSUE TITLE
Some constants are defined twice

### ISSUE THREAD

**Issue by p0nce** [DerelictOrg/DerelictGL3#36]
`GL_FUNC_ADD` is in both `derelict.opengl3.constant` and `derelict.opengl3.deprecatedConstants`.

Also (not exhaustive):
- GL_FUNC_SUB
- GL_FUNC_REVERSE_SUBTRACT
- GL_MIN
- GL_MAX

**Comment by aldacron** [comment]
Thanks. I'll dig into this as soon as I can make time.

**Comment by aldacron** [comment]
It seems all of these were related to the imaging subset of 1.2 and the duplicates should actually be implemented in either 1.4 or as part of ARB_imaging. I think I've got it sorted now. I'll tag a new release once I've settled on an approach for #38.
