### ISSUE TITLE
OpenGL Core 4.5 missing enums

### ISSUE THREAD

**Issue by ParticlePeter** [DerelictOrg/DerelictGL3#39]
In glcorearb.h, 
Khronos $Revision: 32155 $ on $Date: 2015-10-22 23:25:39 -0400 (Thu, 22 Oct 2015),
line 2663, 2664 and 2671

GL_TEXTURE_TARGET                 0x1006
GL_QUERY_TARGET                   0x82EA
GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT 0x00000004

No pull request from my side, I have no idea from which arb extension those came in. How can I find this out?

**Comment by aldacron** [comment]
It generally doesn't take long to narrow down where things are supposed to go. I found an existing GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT_ARB with the same value in arb.d, which belongs to ARB_robustness. KHR_robustness was the extension added to 4.5, but the flag is not listed as a new token in the OpenGL registry, so I added it to constants.d.  The other two are part of the ARB_direct_access extension, to which I was led by Google. I've implemented them and will tak a new release once I've settled on a resolution to #38.

**Comment by ParticlePeter** [comment]
Hi Aldacron,
O.K. the former one I could have figured out, but the later one ? I knew that they do belong to ARB_direct_state_access, but could not find any evidence. And now I see, I searched them with GL_ prefix, but they are listed without on the extension registry page. Learned my lesson, next time a pull request.

**Comment by aldacron** [comment]
> they are listed without on the extension registry page.

Right, the registry doesn't list the GL_ prefix on any new tokens or function names. It's assumed to always be there.
