### ISSUE TITLE
Additional info to glGetnTexImage symbol issue #33 

### ISSUE THREAD

**Issue by ParticlePeter** [DerelictOrg/DerelictGL3#43]
This issue is basically the same as issue #33 but with additional mysterious info.
Same thing on my system ( Kaveri 7800 A-10 with Radeon R7, GN 1.1), glGetnTexImage throws.
I also think that this is a quite old driver bug, even though I have the latest Drivers (Crimson Edition 15.12, Version 15.300.1025.1001) and would like to report it. But before that I need some clarification:

GPU Caps Viewer and GL Extension Viewer both report full GL 4.5 support, except GLSL version (wich is 4.40). Any idea why none of them reports an issue? glGetnTexImage is not an extension, its core 4.5.

It is not possible to avoid the thrown exception with a missingSymbolCallback, what am I missing?
```
ShouldThrow missingSymFunc( string symName )  {

	// glGetnTexImage is a function added in OpenGL 4.5. My app does not use glGetnTexImage,
	// but we still want the rest of OpenGL 4.5. So if we find that glGetnTexImage is missing,
	// don't throw. This will allow OpenGL 4.5 to load - unfortunately not
	if ( symName == "glGetnTexImage" )	return ShouldThrow.No;

	// Any other missing symbol should throw.
	return ShouldThrow.Yes;
}

DerelictGL3.missingSymbolCallback = &missingSymFunc;
DerelictGL3.load();

// Throws:
// derelict.util.exception.SymbolLoadException@e:\Users\Elliot\AppData\Roaming\dub\packages\derelict-util-2.0.4\source\derelict\util\exception.d(35): Failed to load OpenGL symbol [glGetnTexImage]
```
So how can I make sure that this is a Driver Bug before reporting to ATI?
How can I figure out if more symbols are missing if I cannot avoid glGetnTexImage exception?

**Comment by aldacron** [comment]
> It is not possible to avoid the thrown exception with a missingSymbolCallback, what am I missing?

I don't know. What you have there should work. As a first step to find out what's going on, add a writefln to the top of your callback to print symName in brackets: writefln("[%s]", symName). That will tell you if the callback is actually getting called and, if so, verify that there is no whitespace on either end of the symbol string.

> So how can I make sure that this is a Driver Bug before reporting to ATI?

You'll need to put together a test program using something other than Derelict. I recommend doing it with C, using something like [GLEW](http://glew.sourceforge.net/) to load OpenGL. Assuming you've already got a C compiler toolchain set up on your system, it shouldn't take long to slap something together. You can check for 4.5 support with something like this:

```
if(GLEW_VERSION_4_5) { ... }
```

I'm not sure exactly how GLEW handles a missing symbol, but I assume this should be false if a required function is missing. I'll need to dig into the source to be sure.

**Comment by ParticlePeter** [comment]
I tried your suggestion, and nothing gets printed. A debug breakpoint in the callback is never reached. But to be honest I also don't see how the callback could prevent the exception looking at the origin of the thrown exception (in module derelict.opengl3.internal at line 53)
```
        void bindGLFunc( void** ptr, string symName ) {
            import derelict.util.exception : SymbolLoadException;

            auto sym = loadGLFunc( symName );
            if( !sym )
                throw new SymbolLoadException( "Failed to load OpenGL symbol [" ~ symName ~ "]" );
            *ptr = sym;
        }
```

I will try the glew approach.

**Comment by aldacron** [comment]
> I also don't see how the callback could prevent the exception

Yes, you are correct. I wasn't thinking clearly. Nothing loaded via the reload method goes through the missing symbol callback, and that's the way it should be.
