### ISSUE TITLE
Wrong number of attributes in glObjectLabel?

### ISSUE THREAD

**Issue by bioglaze** [DerelictOrg/DerelictGL3#47]
According to https://www.opengl.org/registry/specs/KHR/debug.txt `glObjectLabel`'s signature is 

`void ObjectLabel(enum identifier, uint name, sizei length, const char *label);`

In Derelict's arb.d it's declared as

`alias da_glObjectLabel = void function( GLenum,GLuint,GLsizei,GLsizei,const( GLchar )* );`

Is this a bug? If not, what are the attributes in Derelict's version?

**Comment by mdparker** [comment]
Bug. It's impossible for Derelict to have it's own version of anything, so anytime you see a parameter mismatch like that, it's a bug. Fixed in 1.0.20.
