### ISSUE TITLE
derelict.opengl3.types missing?

### ISSUE THREAD

**Issue by hdon** [DerelictOrg/DerelictGL3#49]
I've tried with 2.0.0-alpha4, 2.0.0-alpha3, 2.0.0-alpha2, and 2.0.0-alpha1.

Every one appears to import derelict.opengl3.types but it doesn't exist in any of these alphas, or at least I can't find it. (It does appear to exist in version 1.0.12, at least.)

```
Package derelict-gl3 can be upgraded from 2.0.0-alpha.3 to 2.0.0-alpha.4.
Use "dub upgrade" to perform those changes.
Performing "debug" build using dmd for x86_64.
derelict-util 3.0.0-alpha.1: target for configuration "library" is up to date.
derelict-gl3 2.0.0-alpha.3: target for configuration "library" is up to date.
derelict-sdl2 3.0.0-alpha.2: target for configuration "derelict-sdl2-dynamic" is up to date.
gl3n 1.3.1: target for configuration "library" is up to date.
balls ~master: building configuration "application"...
src/ants/guisave.d(45,25): Deprecation: instead of C-style syntax, use D-style syntax 'vec4[2] colors'
../../../.dub/packages/derelict-gl3-2.0.0-alpha.3/derelict-gl3/source/derelict/opengl3/deprecatedConstants.d(30,16): Error: module types is in file 'derelict/opengl3/types.d' which cannot be read
import path[0] = source/
import path[1] = src/
import path[2] = ../../../.dub/packages/derelict-gl3-2.0.0-alpha.3/derelict-gl3/source/
import path[3] = ../../../.dub/packages/derelict-util-3.0.0-alpha.1/derelict-util/source/
import path[4] = ../../../.dub/packages/derelict-sdl2-3.0.0-alpha.2/derelict-sdl2/source/
import path[5] = ../../../.dub/packages/gl3n-1.3.1/gl3n
import path[6] = /usr/include/dmd/phobos
import path[7] = /usr/include/dmd/druntime/import
dmd failed with exit code 1.
```

**Comment by mdparker** [comment]
The opengl3 package has been renamed to opengl in the alpha versions and none of the modules in that branch (the 2.0 branch at https://github.com/DerelictOrg/DerelictGL3/tree/2.0) import opengl3.types. Besides which, you have no errors in what you've pasted here related to opengl3.types. The only issue I see is a deprecation warning about your usage of C-style array syntax.

So, what's the problem with opengl3.types?

**Comment by mdparker** [comment]
Sorry. Please disregard my original reply. The error about the types module was beyond the horizontal scroll. I see it now.

**Comment by mdparker** [comment]
OK, I see the problem. Some left over files that shouldn't be there after the refactor. I'll fix it in a few hours. In the meantime you can delete the opengl3 directory from your local copy and you should be good to go.

**Comment by mdparker** [comment]
Actually, that shouldn't be a problem. I've excluded that directory  from the build in dub.sdl. What system are you on?

**Comment by hdon** [comment]
Ubuntu Xenial, DMD v2.072.0... maybe my dub is broken, then?

**Comment by mdparker** [comment]
That's what I'd like to figure out. I'll dig into it as soon as I can.

**Comment by mdparker** [comment]
I'm at a coffee shop on my MacBook Pro. A project I've been compiling on both Windows & OS X using the alpha stuff still compiles. I'll check my Linux laptop at home when I get a chance.

To solve your immediate problem, I've pushed a new 2.0.0-alpha.5 release that removes the opengl3 directory, something which I should have done before. I'll keep this open until we're able to figure out what caused your error.

**Comment by hdon** [comment]
Okay, I just uninstalled dmd/dub and installed latest debian/ubuntu release.

Tentatively I'm going to say I think that fixed the issue but I'm pretty tired :zzz:

**Comment by hdon** [comment]
Okay I have a similar issue when I try to import `derelict.opengl3.deprecatedConstants`

That module imports `derelict.opengl3.types` which does not exist.

**Comment by mdparker** [comment]
For the alpha versions, you shouldn't be importing *anything* from opengl3. That's why I just deleted it for the alpha.5 release. Were you importing it all along?

I ported the deprecated GL stuff over to the new system in alpha.4. If you need to use the deprecated stuff, I suggest for now you just use the 1.0.x series. I'll post a tutorial & documentation on how to use the new 2.0 series when I'm ready to move it out of alpha & beta.

**Comment by mdparker** [comment]
Since I haven't heard anything on this in over a month, I'm closing it. Please reopen it if you have more to report.
