### ISSUE TITLE
 DerelictGL.reload() with default arguments fails on AMD

### ISSUE THREAD

**Issue by p0nce** [DerelictOrg/DerelictGL3#50]
I had a problem with AMD users, ` DerelictGL.reload()` failing on AMD.

The reason is that the default arguments of `reload` load the latest available functions and the function `glGetnTexImage` is not available with AMD (driver is probably at fault).

Can we get around this with `missingSymbolCallback`? No, since ` DerelictGL.reload()` doesn't seem to respect it. This is with derelict-gl3-1.0.21.

I see that there are other issues about this.
What can be done is that the defaults for `DerelictGL.reload()` could disappear. Loading the latest OpenGL is both rare and dangerous.

**Comment by mdparker** [comment]
When `reload` throws an exception, it's absolutely recoverable. At that point, the `loadedVersion` property will be set to the last version that loaded completely. Assuming you require at least OpenGL 3.3:

```
try { DerelictGL3.reload(); }
catch(SymbolLoadException sle) {
    if(DerelictGL3.loadedVersion < GLVersion.GL33) throw sle;
}
```

Another option it to check glGetString (with either GL_VENDOR or GL_RENDERER) for specific vendor names or GPU identifiers and adjust the parameters to reload accordingly.

Loading the maximum available version of OpenGL shouldn't be dangerous. If a driver advertises it supports a specific version, then it should expose every function in that version of the API. However, I'm open to the idea of making the selective symbol loading feature available to `reload`. I think in cases like this, it does make sense to continue loading when you actually need that specific version, but not that specific function.

**Comment by mdparker** [comment]
And for the record, I recently built a new computer with a Radeon RX 480 (my first non-NVIDIA card ever), but have yet to fully set up my dev environment (haven't touched a line of serious code in weeks). I'll get set up this weekend and see if I run into this with the latest drivers. Google isn't really helping me in determining if this has been resolved.

**Comment by p0nce** [comment]
Hi @mdparker 

Some more thoughts about this issue.

- One of the two Vibrant users reporting the issue upgraded her AMD driver, it was with the latest + Windows + a HD 6000.

- I'm sure AMD will fix it at one point, perhaps already has, but the driver can take 6 months to hit the general public, and people with OEM-sanctified drivers won't upgrade anyway. So the isue will still happen for a while regardless of what AMD does.

- Of course this isn't a DerelictGL3 issue but an AMD issue. In my opinion everyone unsuspecting will get hit by this, there is no reason not to be hit. Unless reload does something else by default. Which imho doesn't break separation of responsibility.

- You said DerelictGL allows the discovery of the maximum actually supported OpenGL version. This is a neat feature and a good thing to have, useful for large projects. For the smaller games, not needing functions above say version x.y might be more common I think.

- Since we are 3 or 4 to have been bitten by those missing functions in the AMD driver, it's only fair to say it will happen again.

- I'm pretty sure it isn't the first time OpenGL functions are missing from OpenGL drivers.

- I'll fix the GFM samples to avoid the reload issue and do it like your example code instead.

**Comment by mdparker** [comment]
> For the smaller games, not needing functions above say version x.y might be more common I think.

That's already possible, using the second parameter to reload.

```
DerelictGL3.reload(GLVersion.32, GLVersion.33);
```

This will error out if 3.2 isn't available and will load no higher than 3.3.

**Comment by p0nce** [comment]
That's how I avoid the bug now. For some reason most of use called it like that:

```
DerelictGL3.reload();
 ```
without giving it much thought.

Probably my fault because people would copy the `simpleshader.d` example perhaps. That's why I would be happy if `reload` comes with no default argument, this would make misuse impossible.

**Comment by mdparker** [comment]
I think loading the highest available version (no args) is generally the right thing to do anyway. It sucks that AMD is bugging out like that. But it certainly does make the case for the MissingSymbolCallback. Cause it sucks worse to drop 4.5 completely on every AMD card.

**Comment by p0nce** [comment]
It's your call.

**Comment by mdparker** [comment]
Good news. I just tested loading on my new box with version 16.12.2 of the Crimson drivers. It loads everything with no error. So either your users aren't using and older AMD driver (the latest is actually 17.3.1) or they are using the drivers supplied by the card manufacturer and not AMD. That would be something to look into.

Still going to add MissingSymbolCallback support, though.

**Comment by mdparker** [comment]
Okay, from 1.0.22, `reload` makes use of the `MissingSymbolCallback` attached to the loader. So you can now do this:

```
DerelictGL3.missingSymbolCallback = &callback;
DerelictGL3.reload();
```

I wanted to implement it only for core functions and not for extensions, but I don't think it would have been worth the effort required to do it right. So it works for both core functions and extension functions. I'll work it into the next release of 2.0 as well.
