### ISSUE TITLE
OpenGL 4.6 support

### ISSUE THREAD

**Issue by mdparker** [DerelictOrg/DerelictGL3#55]
Thought I'd add this here before someone else does. It's on my TODO list.

**Comment by tofuninja** [comment]
Is there any work being done to support 4.6 any time soon? If it's not being worked on care to point me in the right direction of doing it myself?

**Comment by mdparker** [comment]
DerelictGL3 is in maintenance mode only. I've ported it over to the BindBC project in bindbc-opengl and added 4.6 support there:

https://github.com/BindBC

Eventually, most of the Derelict packages will be ported over and I'll mark all of this as deprecated. New projects should be using BindBC instead of Derelict where possible.
