### ISSUE TITLE
GL_POLYGON_MODE is erroneously deprecated

### ISSUE THREAD

**Issue by KytoDragon** [DerelictOrg/DerelictGL3#63]
The enum GL_POLYGON_MODE is defined in base_dep.d and is therefore marked as deprecated and not imported unless you pass true as second argument to glFreeFuncs. However, I was unable to find any reference that this value or glPolygonMode were deprecated and the official Khronos site for it (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPolygonMode.xhtml) does not mention any deprecation either. The current C-headers from opengl.org (https://www.khronos.org/registry/OpenGL/api/GL/glcorearb.h) still contain this value.

**Comment by mdparker** [comment]
Thanks!

**Comment by ocornut** [comment]
@mdparker Out of curiosity, do you know/remember what made you mark `GL_POLYGON_MODE` as deprecated in the first place?

It appears that some ATI drivers don't or didn't support it at some point in non-compat 3.2+ profile, but it's unclear there was a driver bug that maybe fed back into different application or software level (if a driver reported a feature to be deprecated it is only understandable that software would just assume it is), or if this was more widely and genuinely deprecated in some specs.

https://community.amd.com/thread/169728
https://github.com/ocornut/imgui/issues/2519

I'm working on a project unrealated to DerelictGL3 but there are so few references to GL_POLYGON_MODE possible deprecation or lack of I felt like asking here. Thank you!
